---
- name: Create application directory
  file:
    path: "{{ webapp_dir }}"
    state: directory
    mode: '0755'

- name: Copier le fichier playbook_stacker.zip
  copy:
    src: playbook_stacker.zip
    dest: "{{ webapp_dir }}/playbook_stacker.zip"
    mode: '0644'

- name: Unarchive application
  ansible.builtin.unarchive:
    src: "{{ webapp_dir }}/playbook_stacker.zip"
    dest: "{{ webapp_dir }}"
    remote_src: yes

#- name: Generate index.html
#  ansible.builtin.template:
#    src: index.html.j2
#    dest: "{{ webapp_dir }}/playbook_stacker/playbook_stacker/index.html"
#    mode: '0644'

- name: Build docker webapp image
  docker_image:
    name: webapp-image
    build:
      path: "{{ webapp_dir }}/playbook_stacker/playbook_stacker"
    source: build

- name: Run contenair webapp1
  docker_container:
    name: webapp1
    image: webapp-image
    state: started
    restart_policy: always
    networks:
      - name: custom_net